### ISSUE TITLE
Precompilation error

### ISSUE THREAD

**Issue by shashins** [kul-forbes/ProximalOperators.jl#72] opened 2019-02-08 15:54 UTC
I am getting following error message while trying to run ```using ProximalOperators``` in Julia 1.1

[ Info: Precompiling ProximalOperators [a725b495-10eb-56fe-b38b-717eba820537]
ERROR: LoadError: LoadError: StackOverflowError:
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /nethome/ssharan31/.julia/packages/ProximalOperators/zHDx9/src/ProximalOperators.jl:3
 [6] top-level scope at none:0
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:328 [inlined]
 [12] eval(::Expr) at ./client.jl:404
 [13] top-level scope at ./none:3
in expression starting at /nethome/ssharan31/.julia/packages/ProximalOperators/zHDx9/src/functions/indFree.jl:33
in expression starting at /nethome/ssharan31/.julia/packages/ProximalOperators/zHDx9/src/ProximalOperators.jl:39
ERROR: Failed to precompile ProximalOperators [a725b495-10eb-56fe-b38b-717eba820537] to /nethome/ssharan31/.julia/compiled/v1.1/ProximalOperators/ez37h.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853

Please suggest how can I fix it. Thanks

**Comment by lostella** [comment] 2019-02-08 16:26
Yes, thanks, that's expected: a fix for this was already merge into mainline, I'll draft a new release later today, so that by upgrading the package the problem will be gone.

Stay tuned.

**Comment by shashins** [comment] 2019-02-08 16:28
Thank you so much. Please let me know whenever you release the updates.

**Comment by lostella** [comment] 2019-02-08 19:06
@shashins v0.10.0 was tagged and added to the Julia registry. Could you try updating the package, and verify that it works?

**Comment by shashins** [comment] 2019-02-08 22:08
@lostella thanks for the update. I updated the package but now I am getting a different error message related to OSQP installation when I try to run ```using  ProximalOperators```

[ Info: Precompiling ProximalOperators [a725b495-10eb-56fe-b38b-717eba820537]
ERROR: LoadError: OSQP not properly installed. Please run Pkg.build("OSQP")
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /nethome/ssharan31/.julia/packages/OSQP/H4U2v/src/OSQP.jl:16
 [3] include at ./boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at ./boot.jl:328 [inlined]
 [8] eval(::Expr) at ./client.jl:404
 [9] top-level scope at ./none:3
in expression starting at /nethome/ssharan31/.julia/packages/OSQP/H4U2v/src/OSQP.jl:13
ERROR: LoadError: LoadError: LoadError: Failed to precompile OSQP [ab2f91bb-94b4-55e3-9ba0-7f65df51de79] to /nethome/ssharan31/.julia/compiled/v1.1/OSQP/BVtcb.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include at ./sysimg.jl:29 [inlined]
 [9] include(::String) at /nethome/ssharan31/.julia/packages/ProximalOperators/y2LPo/src/ProximalOperators.jl:3
 [10] top-level scope at none:0
 [11] include at ./boot.jl:326 [inlined]
 [12] include_relative(::Module, ::String) at ./loading.jl:1038
 [13] include at ./sysimg.jl:29 [inlined]
 [14] include(::String) at /nethome/ssharan31/.julia/packages/ProximalOperators/y2LPo/src/ProximalOperators.jl:3
 [15] top-level scope at none:0
 [16] include at ./boot.jl:326 [inlined]
 [17] include_relative(::Module, ::String) at ./loading.jl:1038
 [18] include(::Module, ::String) at ./sysimg.jl:29
 [19] top-level scope at none:2
 [20] eval at ./boot.jl:328 [inlined]
 [21] eval(::Expr) at ./client.jl:404
 [22] top-level scope at ./none:3
in expression starting at /nethome/ssharan31/.julia/packages/ProximalOperators/y2LPo/src/functions/indPolyhedralOSQP.jl:3
in expression starting at /nethome/ssharan31/.julia/packages/ProximalOperators/y2LPo/src/functions/indPolyhedral.jl:30
in expression starting at /nethome/ssharan31/.julia/packages/ProximalOperators/y2LPo/src/ProximalOperators.jl:47
ERROR: Failed to precompile ProximalOperators [a725b495-10eb-56fe-b38b-717eba820537] to /nethome/ssharan31/.julia/compiled/v1.1/ProximalOperators/ez37h.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853

I ran ]add OSQP but I am still getting the same error.

**Comment by lostella** [comment] 2019-02-08 22:59
It works fine with me with OSQP.jl v0.5.1... Try updating/reinstalling OSQP, or activate a new environment and install ProximalOperators there from scratch.

**Comment by lostella** [comment] 2019-02-08 23:00
What does `] status` give?

**Comment by shashins** [comment] 2019-02-11 17:11
(v1.1) pkg> status
    Status `/home/ssharan31/.julia/environments/v1.1/Project.toml`
  [4d9c3512] JOLI v0.0.0 [`~/.julia/dev/JOLI`]
  [26d9aeca] JUDI v0.1.0 [`~/.julia/dev/JUDI`]
  [ab2f91bb] OSQP v0.5.1
  [a725b495] ProximalOperators v0.10.0
  [d330b81b] PyPlot v2.7.0
  [e2f1b5a8] SeisIO v0.0.0 [`~/.julia/dev/SeisIO`]
  [44cfe95a] Pkg

**Comment by shashins** [comment] 2019-02-11 17:13
I tried reinstalling OSQP but I am still getting the same error message

**Comment by lostella** [comment] 2019-02-11 17:35
Can you try removing OSQP and ProximalOperators completely, and reinstalling them? I cannot really reproduce your problem, and since tests pass in Travis and Appveyor with Julia 1.1, it seems like ProximalOperators v0.10.0 succesfully precompiles on both macos, Linux and Windows...

**Comment by shashins** [comment] 2019-02-11 17:37
I did try completely removing OSQP and ProximalOperators, and reinstalling them. But I am still getting the same error.

**Comment by lostella** [comment] 2019-02-11 17:40
Just to be clear: by "completely removing" them I mean

```
]rm OSQP ProximalOperators
```

followed by

```
rm -r .julia/packages/OSQP
rm -r .julia/packages/ProximalOperators
```

**Comment by shashins** [comment] 2019-02-11 18:07
I tried completely removing the directories also. It seems there is something wrong with OSQP installation. When I reinstall OSQP ```]add OSQP``` I am getting following error message:

Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed OSQP ───────────── v0.5.1
 Installed MathProgBase ───── v0.7.7
 Installed MathOptInterface ─ v0.8.2
  Updating `/home/ssharan31/.julia/environments/v1.1/Project.toml`
  [ab2f91bb] + OSQP v0.5.1
  Updating `/home/ssharan31/.julia/environments/v1.1/Manifest.toml`
  [b8f27783] + MathOptInterface v0.8.2
  [fdba3010] + MathProgBase v0.7.7
  [ab2f91bb] + OSQP v0.5.1
  Building OSQP → `~/.julia/packages/OSQP/H4U2v/deps/build.log`
┌ Error: Error building `OSQP`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  923k  100  923k    0     0  1607k      0 --:--:-- --:--:-- --:--:-- 1607k
│ [ Info: Attempting to create directory /home/ssharan31/.julia/packages/OSQP/H4U2v/deps/downloads
│ [ Info: Downloading file https://dl.bintray.com/bstellato/generic/OSQP/0.5.0/osqp-0.5.0.tar.gz
│ [ Info: Done downloading file https://dl.bintray.com/bstellato/generic/OSQP/0.5.0/osqp-0.5.0.tar.gz
│ [ Info: Attempting to create directory /home/ssharan31/.julia/packages/OSQP/H4U2v/deps/src
│ [ Info: Attempting to create directory /home/ssharan31/.julia/packages/OSQP/H4U2v/deps
│ [ Info: Directory /home/ssharan31/.julia/packages/OSQP/H4U2v/deps already exists
│ [ Info: Attempting to create directory /home/ssharan31/.julia/packages/OSQP/H4U2v/deps/usr/lib
│ [ Info: Attempting to create directory /home/ssharan31/.julia/packages/OSQP/H4U2v/deps/src/osqp-0.5.0/build
│ [ Info: Changing directory to /home/ssharan31/.julia/packages/OSQP/H4U2v/deps/src/osqp-0.5.0/build
│ ERROR: LoadError: IOError: could not spawn `cmake -G 'Unix Makefiles' ..`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:400
│  [2] setup_stdios(::getfield(Base, Symbol("##505#506")){Cmd}, ::Array{Any,1}) at ./process.jl:413
│  [3] _spawn at ./process.jl:412 [inlined]
│  [4] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:725
│  [5] run(::Cmd) at ./process.jl:724
│  [6] run(::BinDeps.SynchronousStepCollection) at /nethome/ssharan31/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521
│  [7] run(::FileRule) at /nethome/ssharan31/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:483
│  [8] run(::BinDeps.SynchronousStepCollection) at /nethome/ssharan31/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521 (repeats 2 times)
│  [9] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /nethome/ssharan31/.julia/packages/BinDeps/ZEval/src/dependencies.jl:944
│  [10] satisfy!(::BinDeps.LibraryDependency) at /nethome/ssharan31/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
│  [11] top-level scope at /nethome/ssharan31/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
│  [12] include at ./boot.jl:326 [inlined]
│  [13] include_relative(::Module, ::String) at ./loading.jl:1038
│  [14] include(::Module, ::String) at ./sysimg.jl:29
│  [15] include(::String) at ./client.jl:403
│  [16] top-level scope at none:0
│ in expression starting at /nethome/ssharan31/.julia/packages/OSQP/H4U2v/deps/build.jl:62
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

**Comment by nantonel** [comment] 2019-02-11 18:41
looks like you need to update cmake see #61

**Comment by shashins** [comment] 2019-02-11 21:12
There was problem with the cmake version on Redhat machine. Needed 3.2 or higher version. I am able to upgrade the cmake version using https://www.heliocastro.info/?p=238. It is working fine now. Thanks

**Closed as completed** 2019-02-11 21:33 UTC
